# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313bdc28e6d9e0f0ceea3ee8282f45c7d27b9a9fa4938309f0a6e4557dbeb5ae52c08620564218595a196e8de3dee5ba5fa7b4685386d12db832f7d9ec223d0b

test:
  secret_key_base: 7ad6896d46ecd8651f712461dc2531eadb2e94fc98771b71b656168a8a9937dbb8a1db550fd717928ade4bfaa21d4faf9f9ed60958b2a71816a16c3879f4ec8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
